(() => {
  let currentPanel;
  let running = false;
  let reviewOrder = 'relevance';
  const clean = (value) => String(value || '').replace(/\s+/g, ' ').trim();
  const node = (tag, text, className) => { const element = document.createElement(tag); if (text !== undefined) element.textContent = text; if (className) element.className = className; return element; };
  const externalLink = (text, href, className) => { const element = node('a', text, className); element.href = href; element.target = '_blank'; element.rel = 'noopener noreferrer'; return element; };
  const log = (event, detail = '') => chrome.runtime.sendMessage({ type: 'staycheck-log', entry: { event, detail, page: location.pathname } }).catch(() => {});

  function flatten(value) { return Array.isArray(value) ? value.flatMap(flatten) : value?.['@graph'] ? flatten(value['@graph']) : [value]; }
  function jsonLdHotel() { for (const script of document.querySelectorAll('script[type="application/ld+json"]')) { try { for (const item of flatten(JSON.parse(script.textContent))) { const types = Array.isArray(item?.['@type']) ? item['@type'] : [item?.['@type']]; if (types.some((type) => ['Hotel', 'LodgingBusiness'].includes(type)) && item.name) { const address = typeof item.address === 'string' ? item.address : [item.address?.streetAddress, item.address?.addressLocality, item.address?.addressRegion, item.address?.postalCode, item.address?.addressCountry].filter(Boolean).join(', '); return { name: clean(item.name), address: clean(address) }; } } } catch { /* Structured data is optional. */ } } }
  function visibleHotel() { const name = clean(document.querySelector('[data-testid="title"], [data-testid="hotel-name"], h1')?.textContent); const address = clean(document.querySelector('[data-testid="address"], [data-testid="property-address"], [data-testid="location"]')?.textContent); return name ? { name, address } : null; }
  function hotel() { return jsonLdHotel() || visibleHotel(); }
  function insertionPoint() { const heading = document.querySelector('[data-testid="title"], [data-testid="hotel-name"], h1'); if (!heading) return null; return heading.closest('[data-testid="hotel-header"], [data-testid="property-header"]') || heading.parentElement?.parentElement || heading.parentElement; }
  function panel() { if (currentPanel?.isConnected) return currentPanel; const target = insertionPoint(); if (!target) return null; currentPanel = node('section'); currentPanel.id = 'staycheck-panel'; currentPanel.setAttribute('aria-live', 'polite'); target.insertAdjacentElement('afterend', currentPanel); return currentPanel; }
  async function request(path, body) { const response = await chrome.runtime.sendMessage({ type: 'staycheck-request', path, body }); if (!response?.ok) throw new Error(response?.error || 'StayCheck could not reach the local companion.'); return response.payload; }

  function header(content, { match = '', expanded = false } = {}) {
    const row = node('div', undefined, 'staycheck-row'); row.append(node('div', '◈', 'staycheck-shield'), node('div', 'StayCheck', 'staycheck-name'));
    const main = node('div', undefined, 'staycheck-main'); main.append(content); row.append(main); if (match) row.append(node('div', `✓ ${match}`, 'staycheck-match'));
    const actions = node('div', undefined, 'staycheck-actions'); const retry = node('button', '↻', 'staycheck-icon-button'); retry.type = 'button'; retry.title = 'Retry Google review check'; retry.onclick = () => start(true); actions.append(retry);
    if (expanded !== null) { const toggle = node('button', expanded ? '⌃' : '⌄', 'staycheck-icon-button'); toggle.type = 'button'; toggle.title = expanded ? 'Hide review excerpts' : 'Show review excerpts'; toggle.dataset.staycheckToggle = 'true'; actions.append(toggle); } row.append(actions); return row;
  }
  function loading(label = 'Finding this property on Google Maps…') { const content = node('div'); content.append(node('div', label, 'staycheck-title'), node('div', 'Matching the property and its address before showing review excerpts.', 'staycheck-subtitle')); return header(content, { expanded: null }); }
  function renderError(message) { const host = panel(); if (!host) return; host.replaceChildren(loading('Google review check unavailable')); host.append(node('div', message, 'staycheck-error')); const retry = node('button', 'Retry Google review check', 'staycheck-retry'); retry.type = 'button'; retry.onclick = () => start(true); host.append(retry); log('check failed', message); }
  function sortedReviews(reviews) { if (reviewOrder !== 'newest') return reviews; return [...reviews].sort((a, b) => Date.parse(b.publishedAt || 0) - Date.parse(a.publishedAt || 0)); }
  function sortControl(place, detailsOpen) { const control = node('div', undefined, 'staycheck-segmented'); for (const [value, label] of [['relevance', 'Relevant'], ['newest', 'Newest shown']]) { const button = node('button', label); button.type = 'button'; button.setAttribute('aria-pressed', String(reviewOrder === value)); button.onclick = () => { reviewOrder = value; log('review order changed', value); renderDetails(place, detailsOpen); }; control.append(button); } return control; }
  function renderDetails(place, detailsOpen = false) {
    const host = panel(); if (!host) return; host.replaceChildren();
    const content = node('div'); const title = node('div', undefined, 'staycheck-title'); title.append(node('span', 'G', 'staycheck-google-mark'), node('span', `Google ${place.rating ?? '—'}`, 'staycheck-rating'), node('span', '★', 'staycheck-star'), node('span', `${place.reviewCount ?? 0} reviews`, 'staycheck-count')); content.append(title, node('div', 'A second opinion before you book', 'staycheck-subtitle'));
    const details = node('div', undefined, 'staycheck-details'); details.hidden = !detailsOpen; const top = node('div', undefined, 'staycheck-detail-top'); top.append(node('p', place.address || 'Address unavailable', 'staycheck-address')); if (place.mapsUrl) top.append(externalLink('Google Maps ↗', place.mapsUrl, 'staycheck-open')); details.append(top);
    const toolbar = node('div', undefined, 'staycheck-review-toolbar'); toolbar.append(node('h3', 'Review excerpts', 'staycheck-section-title'), sortControl(place, detailsOpen)); details.append(toolbar);
    const grid = node('div', undefined, 'staycheck-review-grid'); for (const review of sortedReviews(place.reviews || [])) { const card = node('article', undefined, 'staycheck-review'); card.dataset.rating = String(Math.round(review.rating || 0)); const byline = node('div'); byline.append(review.authorUrl ? externalLink(review.author, review.authorUrl, 'staycheck-review-name') : node('span', review.author, 'staycheck-review-name')); card.append(byline, node('div', `${review.rating}/5 · ${review.relativeDate || ''}`, 'staycheck-review-meta'), node('p', review.text)); if (review.mapsUrl) card.append(externalLink('Open source ↗', review.mapsUrl)); grid.append(card); } details.append(grid);
    details.append(node('p', reviewOrder === 'newest' ? 'Newest shown sorts only these five Google-provided excerpts by date. Open Google Maps for the complete newest-review feed.' : 'Google provides these excerpts in relevance order.', 'staycheck-note'));
    const row = header(content, { match: 'Matched property', expanded: detailsOpen }); row.querySelector('[data-staycheck-toggle]')?.addEventListener('click', () => renderDetails(place, !detailsOpen)); host.append(row, details);
  }
  function renderChoices(candidates) { const host = panel(); if (!host) return; host.replaceChildren(header(node('div', 'Choose the Google Maps listing', 'staycheck-title'), { expanded: null })); const body = node('div', undefined, 'staycheck-details'); body.hidden = false; body.append(node('p', 'StayCheck found multiple possible matches. Choose the correct address before loading reviews.', 'staycheck-address')); for (const place of candidates) { const choice = node('button', undefined, 'staycheck-choice'); choice.type = 'button'; choice.append(node('strong', place.name), document.createElement('br'), node('span', place.address), document.createElement('br'), node('span', `${place.rating ?? '—'} / 5 · ${place.reviewCount ?? 0} reviews`, 'staycheck-meta')); choice.onclick = () => loadDetails(place.id); body.append(choice); } host.append(body); log('match selection needed', `${candidates.length} candidates`); }
  async function loadDetails(placeId) { const host = panel(); if (!host) return; host.replaceChildren(loading('Loading Google review excerpts…')); try { const place = await request('/details', { placeId }); log('review excerpts loaded', `${place.reviewCount || 0} total reviews`); renderDetails(place); } catch (error) { renderError(error.message); } }
  async function start(force = false) { if (running) return; const property = hotel(); const host = panel(); if (!property || !host) { if (force) log('force check failed', 'Hotel heading was not available yet'); return; } running = true; host.replaceChildren(loading(force ? 'Running StayCheck again…' : undefined)); log(force ? 'force check started' : 'automatic check started'); try { const result = await request('/lookup', property); if (result.status === 'matched') { log('property matched', 'Automatic match'); await loadDetails(result.place.id); } else if (result.candidates?.length) renderChoices(result.candidates); else renderError('Google Maps did not return a matching property.'); } catch (error) { renderError(error.message); } finally { running = false; } }
  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => { if (message?.type === 'staycheck-force-run') { start(true); sendResponse({ ok: true }); } });
  let attempts = 0; const observer = new MutationObserver(() => { if (currentPanel?.isConnected) return observer.disconnect(); if (++attempts > 80) { log('panel did not mount', 'Hotel header not found'); return observer.disconnect(); } start(); }); start(); observer.observe(document.documentElement, { childList: true, subtree: true });
})();
